package pt.ulisboa.tecnico.sec;

public enum Opcode {
    CREATE_ACCOUNT, CHECK_ACCOUNT, CREATE_TRANSACTION,
    RECEIVE_TRANSACTION, REQUEST_CHAIN, SERVER_ANSWER,
    AUDIT,REQUEST_SEQUENCE_NUMBER, NO_ANSWER, SOCKET_ERROR, TEST_MESSAGE, ACK, INVALID_SIG
}
